server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/config/mybatis-config.xml
  type-aliases-package: com.coderman.model
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
spring:
  application:
    name: microservice-provider
  datasource:
    username: root # mysql的用户名
    password: zhangyukang # mysql的登入密码
    type: com.alibaba.druid.pool.DruidDataSource # 使用的数据源的类型
    driver-class-name: com.mysql.cj.jdbc.Driver # 使用的数据库驱动
    url: jdbc:mysql://127.0.0.1:3307/cloud_db02?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC # mysql的链接
eureka:
  instance:
    instance-id: microservice-provider-8002 # 修改实例的别名
    prefer-ip-address: true # 显示IP
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka #注册服务到eureka服务器

info:
  app:
    name: microservice-provider-8002
    version: 1.0.0
    author: zhangyukang
